tillhub/tillhub-sdk-javascript

- package-lock.json
- src/errors.ts
- src/tillhub-js.ts
- src/v0/analytics.ts
- src/v0/index.ts
- test/analytics/get_revenues.test.ts
- test/analytics/get_revenues_for_day_of_week.test.ts
added new handler for analytics endpoint
> feat(analytics): added analytics in v0 and added test

- src/v0/analytics.ts
- test/analytics/get_revenues_sum_for_time_range.test.ts
> feat(analytics): added handler for revenues sum for time range

- package-lock.json
- src/errors.ts
- src/tillhub-js.ts
- src/v1/index.ts
- src/v1/transactions.ts
- test/customers/get-meta.test.ts
- test/transactions_v1/get-meta.test.ts
- test/transactions_v1/legacy/get-all.spec.ts
- test/transactions_v1/legacy/pdf.test.ts
Rename v1.Transactions (legacy) to v1.TransactionsLegacy
Create new v1.Transactions (proper)
BREAKING CHANGE: v1.Transactions is no longer using the api endpoint v1/transactions/legacy but
instead v1/transactions
> feat(transactions v1): create new v1.Transactions

- src/uri-helper.ts
- src/v0/analytics.ts
- test/analytics/get_revenues.test.ts
- test/analytics/get_revenues_for_day_of_week.test.ts
- test/analytics/get_revenues_for_hour_of_day.test.ts
- test/analytics/get_revenues_sum_for_time_range.test.ts
- test/uri-helper.test.ts
created uri helper to stringify queries and applied to analytic to avoid undefined errors
BREAKING CHANGE: potential quieres format changes in analytics calls
> fix(uri): created uri helper class to stringify queries

- src/v0/analytics/reports/balances.ts
> fix: fix meta query

- src/errors/index.ts
- src/v1/products.ts
- test/products/get-one-product-children-details.test.ts
- test/products/get-one-product-details.test.ts
add handler for getting parent's children as well as standard product details
> feat(products_v1): add product details

- src/v0/safes.ts
- test/safes/book.test.ts
> feat(safes): Change the url for safes book handler

- src/v0/staff.ts
- test/staff/get-filters.test.ts
gets filters list for search box
> feat(staff): getFilters

- src/v0/analytics.ts
- test/analytics/get_product_groups_report.test.ts
- test/analytics/get_products_report.test.ts
- test/analytics/get_refunds_report.test.ts
- test/analytics/get_staff_overview.test.ts
> feat(analytics): remove trailing “/“

- src/v0/analytics/reports/customers.ts
- test/analytics/customers/get-all.test.ts
- test/analytics/customers/get-filters.test.ts
- test/analytics/customers/get-overview.test.ts
- test/analytics/customers/get-transaction.test.ts
- test/analytics/customers/meta.test.ts
add branch_number to all handlers
> feat(analytics): expand customer query

- src/tillhub-js.ts
- src/v0/index.ts
- src/v0/me.ts
- test/me/get.test.ts
https://tillhub.atlassian.net/browse/TM-4754
> TM-4754 - add new me handler

- src/tillhub-js.ts
- src/v0/index.ts
- src/v0/processes.ts
- test/processes/processes.test.ts
> feat: add processes

- src/v0/auth.ts
- src/v1/auth.ts
include organisation and support login
> feat(auth): add recaptcha_token to all logins

- src/v0/processes.ts
* caused by added pagination on backend
> feat(processes): add next() function to getAll result

- src/v0/branches.ts
BREAKING CHANGE: A new field is defined
DAS-693
> feat(branches): add cost_center to branches

- src/v0/staff.ts
- test/staff/get-pin.test.ts
> feat(staff): add user_id for pin generation

- src/v0/staff.ts
- test/staff/get-pin.test.ts
> feat(staff): add pin length to pin generation

- src/errors/index.ts
- src/v1/registers.ts
- test/registers/search.test.ts
https://tillhub.atlassian.net/browse/DAS-1038
> feat(registers) add registers search

- src/tillhub-js.ts
- src/v0/abocard_systems.ts
- src/v0/index.ts
- test/abocard_systems/abocard_systems.test.ts
https://tillhub.atlassian.net/browse/DAS-1553
> feat(vouchers): add abocard endopints

- src/v0/abocard_systems.ts
- test/abocard_systems/abocard_systems.test.ts
https://tillhub.atlassian.net/browse/DAS-1553
> fix(vouchers): adjust abocard API path

- src/errors/productAddonGroups.ts
- src/errors/productAddons.ts
- src/tillhub-js.ts
- src/v0/index.ts
- src/v0/product_addon_groups.ts
- src/v0/product_addons.ts
- test/product_addon_groups/create.test.ts
- test/product_addon_groups/get-all.test.ts
- test/product_addon_groups/get.test.ts
- test/product_addon_groups/meta.test.ts
- test/product_addon_groups/put.test.ts
- test/product_addons/create.test.ts
- test/product_addons/get-all.test.ts
- test/product_addons/get.test.ts
- test/product_addons/meta.test.ts
- test/product_addons/put.test.ts
https://tillhub.atlassian.net/browse/DAS-1754
> DAS-1754 -  Add add-ons and add-on groups to SDK

- test/product_addon_groups/create.test.ts
- test/product_addon_groups/get-all.test.ts
- test/product_addon_groups/get.test.ts
- test/product_addon_groups/meta.test.ts
- test/product_addon_groups/put.test.ts
- test/product_addons/get-all.test.ts
- test/product_addons/meta.test.ts
Just added fixed commit messages
> FIX - DAS-1754 - Add add-ons and add-on groups to SDK

- src/tillhub-js.ts
- src/v1/branches.ts
- src/v1/index.ts
- test/branches_v1/get-all.test.ts
- test/branches_v1/get-one.test.ts
https://tillhub.atlassian.net/browse/DAS-1744
> DAS-1744 - Branches v1

- src/base/handler.ts
- src/base/index.ts
- src/tillhub-js.ts
- src/v2/analytics/reports/stocks.ts
- src/v2/analytics/reports/transactions-items.ts
- test/analytics_v2/stocks/index.test.ts
https://tillhub.atlassian.net/browse/DAS-1751
Please ask if you need more information or just to understand what's going on here.
> feat(reports/v2/stocks): adjust response to v2 format

- src/v1/customers.ts
- test/customers-v1/count.test.ts
- test/customers-v1/create.test.ts
- test/customers-v1/delete.test.ts
- test/customers-v1/get-meta.test.ts
https://tillhub.atlassian.net/browse/DAS-2043
> feat(customers): migrate customers API to V1

- src/v1/vouchers.ts
- test/vouchers/meta.test.ts
https://tillhub.atlassian.net/browse/DAS-2090
> feat(vouchers): migrate vouchers meta to V1

- src/v1/products.ts
https://tillhub.atlassian.net/browse/DAS-2172
> feat(products): add options to product getDetalis request

- src/v1/analytics/reports/vouchers.ts
- test/analytics_v1/vouchers/index.test.ts
https://unz.atlassian.net/browse/UNTIL-5883
> feat(vouchers): add pagination support to voucher statistics

- src/v1/products.ts
[UNTIL-1968](https://unz.atlassian.net/browse/UNTIL-1968)
[UNTIL-1968]: https://unz.atlassian.net/browse/UNTIL-1968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(products): add query params option to meta method

- src/v1/analytics/reports/vouchers.ts
- test/analytics_v1/vouchers/index.test.ts
https://unz.atlassian.net/browse/UNTIL-5883
> fix(vouchers): change data structure in vouchers reports

- src/tillhub-js.ts
- src/v0/index.ts
- src/v0/service_category.ts
- test/service_category/create.test.ts
https://unz.atlassian.net/browse/UNTIL-7135
> feat(reservations): create a new service category (#7135)

- src/v0/service_category.ts
- test/service_category/get-all.test.ts
https://unz.atlassian.net/browse/UNTIL-7137
> feat(reservations): add getAll service categories (#7137)

- src/v0/service_category.ts
- test/service_category/put.test.ts
https://unz.atlassian.net/browse/UNTIL-7139
> feat(reservations): add put service categories (#7139)

- src/tillhub-js.ts
- src/v0/index.ts
- src/v0/services.ts
- test/services/create.test.ts
https://unz.atlassian.net/browse/UNTIL-7145
> feat(reservations): create service (#7145)

- src/v0/staff.ts
- test/staff/create.test.ts
- test/staff/get-services.test.ts
- test/staff/put.test.ts
https://unz.atlassian.net/browse/UNTIL-7336
> feat(staff)  add method for getting staff services (Feat/until 7336)

- src/tillhub-js.ts
- src/v0/holidays.ts
- src/v0/index.ts
- test/holidays/get-all.test.ts
https://unz.atlassian.net/browse/UNTIL-7578
> feat(holidays) add Holidays entity with a get all method (#7578)

- src/tillhub-js.ts
- src/v0/index.ts
- src/v0/shift_plan.ts
- test/shift_plan/get.test.ts
- test/shift_plan/put.test.ts
https://unz.atlassian.net/browse/UNTIL-8334
> feat(shift plan): Add get/put requests for Shift Plan (Feat/until 8334)

- src/v0/shift_plan.ts
- test/shift_plan/get.test.ts
- test/shift_plan/put.test.ts
https://unz.atlassian.net/browse/UNTIL-8334
> feat(shift plan): refactor types to use an array syntax

- src/tillhub-js.ts
- src/v0/document_exports.ts
- src/v0/documents.ts
- src/v0/index.ts
- test/document_exports/get-all.test.ts
> UNTIL-9181 Support for requesting export-history exports

- src/v0/documents.ts
> feat(documents): support correlation id when downloading expired document

- src/v0/configurations.ts
https://unz.atlassian.net/browse/UNTIL-9144
> feat(configuration): add reservations key (UNTIL 9144)

- src/v0/branches.ts
- src/v0/shift_plan.ts
- test/shift_plan/get.test.ts
- test/shift_plan/put.test.ts
https://unz.atlassian.net/browse/UNTIL-9124
> feat(shift plan): remove branch id parameter (UNTIL 9124)

- src/v1/products.ts
- test/products/select.test.ts
https://unz.atlassian.net/browse/UNTIL-10440
> feat(products): add list method for fetching products by ids (UNTIL 10440)

- src/v1/branches.ts
[UNTIL-9317](https://unz.atlassian.net/browse/UNTIL-9317)
[UNTIL-9317]: https://unz.atlassian.net/browse/UNTIL-9317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(branches): add extended as query option

- src/v0/branch_groups.ts
https://unz.atlassian.net/browse/UNTIL-11238
> feat(branch_groups): add available_in_online_booking prop (UNTIL 11238)

- src/v0/branches.ts
https://unz.atlassian.net/browse/UNTIL-11239
> feat(branches): add available in online booking field (UNTIL 11239)

- src/tillhub-js.ts
- src/v1/appointment_reminders.ts
- src/v1/index.ts
- test/appointment_reminders_v1/create.test.ts
- test/appointment_reminders_v1/get.test.ts
- test/appointment_reminders_v1/patch.test.ts
https://unz.atlassian.net/browse/UNTIL-11465
> feat(appointment_reminder): add appointment reminder entity (UNTIL 11465)

- src/v1/appointment_reminders.ts
- test/appointment_reminders_v1/create.test.ts
- test/appointment_reminders_v1/get.test.ts
- test/appointment_reminders_v1/patch.test.ts
https://unz.atlassian.net/browse/UNTIL-12146
> fix(appointment-reminders): update appointment reminder type (UNTIL 12146)

- src/v1/appointment-reminder-templates.ts
- src/v1/appointment_reminders.ts
- src/v1/index.ts
- test/appointment_reminder_templates_v1/get.test.ts
- test/appointment_reminders_v1/templates.test.ts
https://unz.atlassian.net/browse/UNTIL-12146
> feat(appointment-reminders): add endpoint for templates (UNTIL 12146)
